export const GET_USERS = 'GET_USERS'
export const GET_TODOS = 'GET_TODOS'
export const REMOVE_TODO = 'REMOVE_TODO'
export const ADD_TODO = 'ADD_TODO'
export const CHANGE_FAVORITES = 'CHANGE_FAVORITES'
export const SET_PROVIDER = 'SET_PROVIDER'